language: emacs-lisp
sudo: false
# Allow Emacs snapshot builds to fail and don’t wait for these as they can take
# a looooong time
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=snapshot
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  # Install Texinfo, if you need to build info manuals for your project
  - make -f emacs-travis.mk install_texinfo
install:
  # Install your dependencies
  - cask install
script:
  # Run tests here
  # - cask exec ert-runner
  - make archive

deploy:
  provider: s3
  alc: public_read
  access_key_id: AKIAIVILKMX5NOX57MAQ
  secret_access_key:
    secure: qtXftaIfMzuVlN2IccU+IgYCMw52YLOdFgF5zAPaixqlUGDs/ahAZLitnA6JDcWtrQShJHX9pd5s98yRRBFlBgzx2F/FWbH/23zSBTXyBIIvz3F+edpuuz/HFYDI97xdb++Pca25eoSxE3uWlJ4blA1mUpPElGch6dL26EX5d4/kPCJx5J9OaLlGtEoPVQAO8puEsckTRqfVXMKRgbU9h4LaBRr8glDbYPjv2ETxysAKuWWSg00lLfjEArs3FHObSWPgBLhDadWu+SkxbrdkkwU26DMz1idGuOG/Qx5QjZV+qvMwv9T6FxaQIzBWny6zf/zfGIkVUX99XhLxytYaexAIPAYim4uFtYVwAwtoSilYRyVcDeMHHJumTWVYSZU4StCgB0g02ibfTs/x488G7vBytA/Tljk70JPaSLT6ltR1AAiOJG37DMv9mUSlR8Bnh0hTQMg6JGgIR2x3x0XtnL/7QeNoM1PjA+32qXQwldqfOJ9uQ5+Tht3xWBAyspcNtMgJe3izeaMecc0dggQXfRrGiTQdnNbcNDD6fZfsZlzWej365HnMpjhMbug1f4p5MxK1zIaAzbb9VVTvXB7UU0i2VB4MhciFs2x+lWFYpje/MccmahtrAjdL366dLAMYX2598Crx+WoiEN+7xaB9g+nY34k1mzy8ve1xiM20jts=
  bucket: elpa.frontside.io
  region: us-east-2
  skip_cleanup: true
  local_dir: dist/packages
  on:
    branch: master
    condition: $EMACS_VERSION = 25.1
