language: emacs-lisp
sudo: false
# Allow Emacs snapshot builds to fail and don’t wait for these as they can take
# a looooong time
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=snapshot
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  # Install Texinfo, if you need to build info manuals for your project
  - make -f emacs-travis.mk install_texinfo
install:
  # Install your dependencies
  - cask install
script:
  # Run tests here
  # - cask exec ert-runner
  - make archive

deploy:
  provider: s3
  access_key_id: AKIAJT22SMUBIRR3MNZQ
  secret_access_key:
    secure: m/xPPvLok5fO8ourtA6ZfsWT+I4mEhiVEq9bn13Ze53G215bdjaY1kp2c+BBt8NSi0vB+sHv4M27ygvVmm7cOPOgaBCZzIcptwDpJqmZHkFUrE1DwfvYMdXlQL3C3EqQiPPvfNCVgstNKqN2BZfXGTIKEzzPHFRxCPSOBRoF2StxllF181YzBFcTycjs35hFiWy3Bh6n4W11Zm9wexw2ZhAQ25jK5MGOVt5rdwaD5WKd50L3JU170MS+1SIWqIB7JpKwXGHigPk64RdvV5S1P3SMk2zaYL2BuGUwAhsNkKsmsk84iiUZGiqJ8D4/DSxnB8QdKgBNA5ba0xbuKlbqfhSXQIs2a+4HvDur+wQA4Qrqkfu4DAzjgMlcnnNmY+SUGX/OvNfA6Sfno3vWWqh1uP4gtyBS+/9niqhjfPeez8v7VlM0Lp0Z7cQ2CAkCscWzq9BQg+QnWPNnwOba33scGu9cQgzKj9pVQZ+N+AR8lGHzVvUkTAj3Q3s2duRPZdLnOkzw1EL5EtovZ+s9JVsuGyGnkNrryKj+LTQwBOAP72p5MVoRRr4MjTjEI3jH0iDymjKqCJsjhstsQszL+I+plmWyoZgdYUGGKEbmNbVaDdcDF+//UUvWjKmIbuVOYt0O2+OfZYLcbxK4OCOPJWJRymHEcZEFFuqX5wj8Xbijmow=
  bucket: elpa.frontside.io
  region: us-east-2
  skip_cleanup: true
  local_dir: dist/packages
  on:
    branch: master
